### ISSUE TITLE
AUR install fails with "/usr/share/glib-2.0/schemas/gschemas.compiled exists in filesystem"

### ISSUE THREAD

**Issue by jokuNimi** [bil-elmoussaoui/Icon-Requests#10]
Installing from AUR with aura fails with the error message
```
error: failed to commit transaction (conflicting files)
icon-requests: /usr/share/glib-2.0/schemas/gschemas.compiled exists in filesystem
Errors occurred, no packages were upgraded.
```

**Comment by bilelmoussaoui** [comment]
Will fix that in few minutes

**Comment by bilelmoussaoui** [comment]
Fixed ;)

**Comment by jokuNimi** [comment]
Thanks, now it installs. I think there's an issue with permissions, though:
```
$ ls -l /usr/bin/icon-requests 
-rw-r--r-- 1 root root 1841 Mar 18 12:17 /usr/bin/icon-requests
```
```
$ ls -l /usr/share/applications/icon-requests.desktop
-rw-r--r-- 1 root root 434 Mar 18 12:17 /usr/share/applications/icon-requests.desktop
```
I can get it to launch after adding executable permissions to /usr/bin/icon-requests.

Thanks for response and the application!

**Comment by bilelmoussaoui** [comment]
Hmm, AUR added recently the hooks to compile gschema files and refresh the icon cache. I thought they have done the same for the executable files under `/usr/bin` I will take a look and see if it's an upstream issue or not :)

**Comment by bilelmoussaoui** [comment]
Fixed that on master using meson (build system). I will create a new hotfix release this evening! thanks for using the application!

**Comment by jokuNimi** [comment]
Thanks for the fix! I really like the idea of the application. I wish I could help with something, but I don't have any expertise to solve any of the current issues. I could add Finnish translations if you think that would be useful? Would you like feature requests? I don't want to come off as pestering if this is not a project you want to commit a lot of time to.

**Comment by bilelmoussaoui** [comment]
@jokuNimi Just provide the translation! that would be really awesome:+1:  and if you have any ideas, feature requests or anything just open a new issue and let's discuss it :) the application was originally built for Numix theme, and i just thought about making it work with other themes would be really helpful for other icon designers
