### ISSUE TITLE
Some issues with the .pot translation file

### ISSUE THREAD

**Issue by jokuNimi** [bil-elmoussaoui/Icon-Requests#12]
I made a [translation](https://gist.github.com/jokuNimi/745fd4ed035cc3ac47afdf003c0935e6) based on the .pot file. There are some issues with it though:
- The icon name "icon-requests" is set to be translatable
- I'm not sure how the .desktop file Keywords key is best handled, but I translated it for now
- Some of the header text of the .pot file seems to be a placeholder
- A few important strings are missing, especially the "All", "Unspported" and "Hardcoded" tab headings. I'll attach images of what poedit would want to add and remove based on the source code, but I wouldn't trust those too much; this is the first time I'm using the program so some settings might be off.
- The string "Please check your connexion" should probably say "connection", but maybe it's a stylistic choice :)

*Strings to add*
![strings to add](https://cloud.githubusercontent.com/assets/8011580/24072293/ed3bc5f2-0bed-11e7-9c33-829c455b304b.png)

*Strings to remove*
![string to remove](https://cloud.githubusercontent.com/assets/8011580/24072294/f1f094f6-0bed-11e7-8ee3-1c350eb77407.png)

I'm not very familiar with the translation process, so sorry if there are some misunderstandings on my end.

**Comment by bilelmoussaoui** [comment]
My english isn't that good, if you can fix those strings that would be awesome! just open a text editor and look for strings that start with `_("I'm a translated string")` and replace the string. I will regenerate the pot file later. I will see how to fix the rest of the reported issues tomorrow

**Comment by jokuNimi** [comment]
I tried to look into these issues a bit. Sorry if this is a bit long :)

- In the [desktop entry specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys) `Icon` is of type `localestring`, so translating is probably correct behaviour for `xgettext`. It still doesn't seem to make sense, especially as the i[con naming specification](
https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html) states that

   "Icon names are in the en_US.US_ASCII locale. This means that the allowable characters in the icon names, must fall withing the US-ASCII character set. As a further restriction, all icon names may only contain lowercase letters, numbers, underscore, dash, or period characters. Spaces, colons, slashes, and backslashes are not allowed. Also, icon names must be spelled as they are in the en_US dictionary."

  Possibly the translated string would be used as a DisplayName from the [icon theme specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#file_formats). Anyway, this isn't an issue for this app. A reasonable course of action is probably to leave the string untranslated or have it be identical to the english if there are problems.

- Keywords is a `localestring` in the [desktop entry specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys) and that seems to make sense. So there's no real issue here.

- Not sure about the header text. It probably doesn't matter much.

- I ran the `update_pot.sh` script, and it complains about the language "ui" being unknown and the extension "xml" being unknown in `./data/icon-requests.appdata.xml.in`. The first error is cleared (and the correct strings are added) by changing line 22 from `--language=ui` to `--language=Glide`. I couldn't make any sense of the appdata file situation. According to the gettext manual it should support [appdata](https://www.gnu.org/software/gettext/manual/gettext.html#AppData), but appdata isn't listed as one of the supported [languages](https://www.gnu.org/software/gettext/manual/gettext.html#Choice-of-input-file-language). It might just be that the docs are out of date, but I'm stuck here. I tried putting the appdata file in `po/POTFILES.in` and running `xgettext -f po/POTFILES.in` as per a guide on [using modern gettext](https://blogs.gnome.org/mclasen/2016/07/21/using-modern-gettext/), but got the same error.

- I can proofread the English as well, but that would probably be easier to do when the translations are in order. That would make the strings easier to find. I could do it beforehand as well if you don't want to work on the translations.

**Comment by bilelmoussaoui** [comment]
Should be fixed on my latest commit

**Comment by bilelmoussaoui** [comment]
@jokuNimi Can you confirm that please?

**Comment by jokuNimi** [comment]
@bil-elmoussaoui The pot file seems good to me now, and running the script reports no errors.

**Comment by bilelmoussaoui** [comment]
Perfect :) can you still translate the app ?
