### ISSUE TITLE
Allow resizing the window

### ISSUE THREAD

**Issue by jokuNimi** [bil-elmoussaoui/Icon-Requests#15]
Currently on my system (arch linux with GNOME Shell 3.22.3) I can't resize the application window. That might be a reasonable ui choice, but personally 
- I feel less in control of an applicatoin if I can't resize it
- It stops my normal workflow of positioning the window using super-arrowkey
- It makes the window hard to move generally, since there isn't much space in the header to grab onto.

**Comment by bilelmoussaoui** [comment]
I really don't want to make the window resizable. It's not needed at all...
