### ISSUE TITLE
Add help documentation

### ISSUE THREAD

**Issue by jokuNimi** [bil-elmoussaoui/Icon-Requests#16]
I don't know what audience the application is planned for, but it would be nice if it easily usable for anyone. A guide on how the application works might then be useful. I have three main ideas on how it could be implemented
- tooltips in the application. For example it wasn't obvious for me what exactly "Report" means, and it might not be obvious for everyone what "Hardcoded" means. Hovering over those buttons could open a tooltip on what it means.
- some sort of a help dialog that opens from the menu. I have no idea how hard this it to implement.
- just adding some text to the readme file here on github.

**Comment by bilelmoussaoui** [comment]
If you want to add some information on the readme file just open a PR :+1: and i will merge it

**Comment by bilelmoussaoui** [comment]
Closing this, other information will be provided later in the future as a help documentation. If anyone wants to add any useful stuff to the README feel free to do so.
