### ISSUE TITLE
Some apps with icon pack's icons are in "Unsupported"

### ISSUE THREAD

**Issue by theel0ja** [bil-elmoussaoui/Icon-Requests#19]
![image](https://cloud.githubusercontent.com/assets/5832930/24301812/3bee092e-10b9-11e7-97fb-bebaf7b9e44f.png)

**Comment by bilelmoussaoui** [comment]
Hmmm pretty weird :( can you try using an other theme? How did you installed your theme?

**Comment by theel0ja** [comment]
Works with Mint-X (default Mint theme), but when I switch back (restarted between theme changes), Numix Circle has that problem... But, those apps that aren't themed in Mint-X is in that "Unsupported" tab with Numix Circle...

**Comment by theel0ja** [comment]
GConf says that my icon theme is Mint-X, while it's really Numix-Circle. Also the theme seems to be in GConf Mint-X, while it's really Mint-Y...

![image](https://cloud.githubusercontent.com/assets/5832930/24304428/fb5bda18-10c1-11e7-8350-7df18bb514a4.png)

**Comment by bilelmoussaoui** [comment]
Well report that issue to mint :( I'm just reading the dconf value. If Mint isnt setting the value correctly I cant do anything about it... At worst you can set the value manually

**Comment by theel0ja** [comment]
Reported.

**Comment by bilelmoussaoui** [comment]
Thanks for investigating ! :+1:

**Comment by theel0ja** [comment]
Works now, if I select theme from gnome-tweak-tool (that don't apply to Cinnamon).

**Comment by bilelmoussaoui** [comment]
Perfect!
