### ISSUE TITLE
Fix Numix Circle for Numix Theme icons

### ISSUE THREAD

**Issue by theel0ja** [bil-elmoussaoui/Icon-Requests#20]
numix-icon-theme-circle is using numix-icon-theme for some icons, like that `reload` icon in Cinnamon Killer Daemon, so it could ignore that...

![image](https://cloud.githubusercontent.com/assets/5832930/25047118/bd5fa71c-213d-11e7-9910-c447c9418de8.png)

**Comment by bilelmoussaoui** [comment]
Nop, it's not Numix circle is fault, but it's cinnamon's fault for using Actions icons for applications icons and by then not following freedesktop standards :( i have been reporting those kind of issue on Mint recently; Feel free to report that upstream please

**Comment by bilelmoussaoui** [comment]
But i can add a "ignore" option, where the user can ignore the application from showing as unsupported for that theme...

**Comment by theel0ja** [comment]
Ok. Closing.
